{
 "title": "Highvoltagesystem",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Dutycycle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"dutyCycle\"\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"frequency\"\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"voltage\"\n    }\n  }\n]"
    }
   ]
  }
 ]
}