{
 "title": "Vacuumsystem",
 "time": { "from": "2025-03-15T09:10:48.000Z", "to": "2025-03-15T09:11:50.000Z" },
 "panels": [
  {
   "title": "Temperature outside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"temperature_2\"\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Temperature inside",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"temperature_1\"\n    }\n  }\n]"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurembar" } },
   "targets": [
    {
     "collection": "SensorData",
     "queryLanguage": "json",
     "queryText": "[\n  {\n    \"$match\": {\n      \"sensor_name\": \"pressure_1\"\n    }\n  }\n]"
    }
   ]
  }
 ]
}