version: '3.8'
services:
  mongodb:
    image: arm64v8/mongo:4.4.6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - ./mongo/data:/data/db

  flask_app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      networks:
        - app_network
      environment:
        - FLASK_ENV=development
        - FLASK_APP=/opt/FFRHAS/HAS/App.py

  grafana:
    image: grafana/grafana-oss:latest-ubuntu
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-mongodb-datasource
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - ./grafana/grafana_custom:/etc/grafana
      - ./grafana/grafana_storage:/var/lib/grafana
      - ./grafana/mongodb_datasource:/var/lib/grafana/plugins/haohanyang-mongodb-datasource
    depends_on:
      - mongodb

networks:
  app_network:
    driver: bridge
