version: '3'
services:
  mongodb:
    image:  arm64v8/mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  app:
    build:
      context: .
    container_name: ffrhas-app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./FFRHAS:/opt/FFRHAS
    command: python3 /opt/FFRHAS/HAS/app.py
