version: '3'
services:
  mongodb:
    image: arm64v8/mongo:4.4.6
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  app:
    build:
      context: .
    container_name: ffrhas-app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./FFRHAS/HAS:/opt/FFRHAS/HAS
    command: python3 /opt/FFRHAS/HAS/app.py

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/data:/var/lib/grafana
